name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Format + lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"
      - name: Set up environment
        run: |
          uv sync
          source .venv/bin/activate
      - name: Run pre-commit
        run: |
          uvx pre-commit run \
            --show-diff-on-failure \
            --color=always \
            --all-files \
            --hook-stage manual

  checks:
    name: Run make_figures.sh
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v7

      - name: Run make_figures.sh
        run: bash make_figures.sh
